let state={company:'Acme Technologies',research:null,analysis:null,transcript:''},$=id=>document.getElementById(id);
function go(id){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');scrollTo(0,0)}
async function startResearch(name){state.company=name||$('companyInput').value.trim()||state.company;go('research');$('researchTitle').textContent=state.company;$('researchContent').innerHTML='<article><b>Researching…</b><p>Only source-backed claims should appear in production.</p></article>';try{state.research=await(await fetch('/api/research?company='+encodeURIComponent(state.company))).json();renderResearch()}catch(e){$('researchContent').innerHTML='<article>Research failed: '+esc(e.message)+'</article>'}}
function renderResearch(){let r=state.research,s=r.snapshot,h='<article><div class="note"><b>Evidence rule:</b> Unknown information is not inferred; it becomes a discovery gap.</div><h2>Company Overview</h2><div class="grid">'+[['Industry',s.industry],['Founded',s.founded],['Global HQ',s.global_hq],['India presence',s.india_presence],['Employees',s.employees],['Status',s.status],['Business',s.description]].map(x=>'<div class="fact"><small>'+esc(x[0])+'</small><b>'+esc(x[1])+'</b></div>').join('')+'</div></article>';
h+='<article><h2>Recent Changes & Growth Signals</h2>'+(r.signals.length?r.signals.map(x=>'<div class="item"><b>'+esc(x.type)+'</b><p>'+esc(x.text)+'</p><small>Source: '+esc(x.source)+'</small></div>').join(''):'<p>None reliably available.</p>')+'</article>';
h+='<article><h2>Conversation Angles</h2><small>AI hypotheses derived from verified signals — not facts.</small>'+(r.angles.map(x=>'<div class="angle"><b>'+esc(x.title)+'</b><p>'+esc(x.text)+'</p><small>Basis: '+esc(x.basis)+'</small></div>').join('')||'<p>None.</p>')+'</article>';
h+='<article><h2>Discovery Gaps</h2>'+r.gaps.map(x=>'<div class="gap"><b>'+esc(x)+'</b><span> MUST DISCOVER</span></div>').join('')+'</article>';
h+='<article><h2>Recommended Questions</h2>'+r.questions.map((x,i)=>'<div class="question"><b>'+ (i+1)+'.</b> '+esc(x)+'</div>').join('')+'</article>';$('researchContent').innerHTML=h}
function showPaste(){$('pasteBox').classList.remove('hidden');$('analyseBtn').classList.remove('hidden');$('pasteBox').focus()}
function loadDemoTranscript(){state.transcript=`SDR: I noticed Acme has been growing and expanding across locations. What are you currently using for HR?
Prospect: We're currently using Darwinbox. Our biggest issue is attendance reconciliation. The HR team spends a lot of time fixing discrepancies every month.
SDR: You're looking at improving this in Q1 next year, correct?
Prospect: Yes, we're evaluating options for Q1 2027.
SDR: Great. Let me show you how Keka can help with attendance and payroll.
Prospect: Sure. We'd like to see a demo.
SDR: I'll schedule that.`;$('pasteBox').value=state.transcript;showPaste()}
function loadFile(e){let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{state.transcript=String(r.result);runAnalysis()};r.readAsText(f)}
function analysePasted(){state.transcript=$('pasteBox').value.trim();if(!state.transcript)return alert('Paste a transcript first.');runAnalysis()}
async function runAnalysis(){go('analysis');$('analysisContent').innerHTML='<article><b>Analysing transcript…</b></article>';if(!state.research)state.research=await(await fetch('/api/research?company='+encodeURIComponent(state.company))).json();let a=await(await fetch('/api/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({company:state.company,research:state.research,transcript:state.transcript})})).json();state.analysis=a;renderAnalysis(a);renderNext(a)}
function badge(s){return '<span class="'+(s==='established'?'ok':'warn')+'">'+(s==='established'?'✓ Established':'— Not established')+'</span>'}
function renderAnalysis(a){let h='<article class="note"><b>Evidence-based review:</b> No overall call-quality score is generated.</article><article><h2>What Was Discovered</h2>'+a.discovered.map(x=>'<div class="okbox">✓ '+esc(x)+'</div>').join('')+'</article><article><h2>Discovery Status</h2><div class="grid">'+a.findings.map(x=>'<div class="fact"><b>'+esc(x.category)+'</b>'+badge(x.status)+'</div>').join('')+'</div></article><article><h2>What Was Missed</h2>'+((a.missed.length?a.missed:['No major missed opportunities detected.']).map(x=>'<div class="gap">'+esc(x)+'</div>').join(''))+'</article><article><h2>Need, Budget, Authority & Timeline</h2>'+a.findings.filter(x=>['Need','Impact','Budget','Authority','Timeline'].includes(x.category)).map(x=>'<div class="item"><b>'+esc(x.category)+' '+badge(x.status)+'</b><p>'+esc(x.evidence)+'</p></div>').join('')+'</article><article><h2>Research → Call</h2>'+((state.research.signals||[]).map(x=>'<div class="item"><b>'+esc(x.type)+'</b><p>'+esc(x.text)+'</p></div>').join('')||'<p>No pre-call signals.</p>')+'</article><article><h2>Coaching</h2><div class="okbox"><b>What worked</b><p>'+a.discovered.slice(0,3).map(esc).join('<br>')+'</p></div><div class="gap"><b>Improve next</b><p>'+a.missed.slice(0,3).map(esc).join('<br>')+'</p></div></article>';$('analysisTitle').textContent='Post-call analysis — '+a.company;$('analysisContent').innerHTML=h}
function renderNext(a){$('nextCompany').textContent=a.company;$('nextContent').innerHTML='<article class="note"><b>Next-call principle:</b> Resolve the highest-value unknowns first. Do not repeat established information.</article>'+(a.next_actions.map((x,i)=>'<article><span class="priority">'+esc(x.priority)+'</span><h2>'+ (i+1)+'. '+esc(x.objective)+'</h2><p><b>Question:</b> '+esc(x.question)+'</p></article>').join('')||'<article><h2>No urgent next-call gaps detected</h2></article>')+'<article><h2>Suggested Flow</h2><p>Confirm context → Deepen need → Establish authority → Timeline & budget → Agree next step</p></article>'}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}